baseURL = 'https://benqqqq.github.io/'
languageCode = 'en-us'
title = 'Let me make bug for you'
theme = 'PaperMod'

[menu]
[[menu.main]]
    name = 'About'
    pageRef = '/about'

[[menu.main]]
    name = 'Tags'
    pageRef = '/tags'
#[[menu.main]]
#    name = 'GitHub'
#    url = 'https://github.com/benqqqq/'
#[[menu.main]]
#    name = 'LinkedIn'
#    url = 'https://www.linkedin.com/in/ming-chi-wu-46122943/'
